on:
  workflow_call:
    inputs:
      actions_os:
        type: string
        required: true
        description: "The GHA runner Virtual Environment to use for the build"
      dotnet_runtimes:
        type: string
        required: true
        description: "Stringified JSON Array of dotnet runtimes to build against"

jobs:
  build:
    name: Build Jellyfin Server
    runs-on: ${{ inputs.actions_os }}

    strategy:
      fail-fast: false
      matrix:
        dotnet_runtime: ${{ fromJson(inputs.dotnet_runtimes) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: "6.0.x"

      - name: Build
        shell: bash
        run: |-
          mkdir bin
          dotnet publish Jellyfin.Server \
            --configuration Release \
            --self-contained true \
            --runtime ${{ matrix.dotnet_runtime }} \
            --output bin \
            --nologo \
            -p:DebugSymbols=false \
            -p:DebugType=none \
            -p:UseAppHost=true
          tar -cf server-build_${{ matrix.dotnet_runtime }}.tar -C bin .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          retention-days: 30
          name: server-build_${{ matrix.dotnet_runtime }}
          path: server-build_${{ matrix.dotnet_runtime }}.tar
