name: "🏗️ Build CI"

on:
  push:
    branches:
      - "master"
      - "release-*"
    paths-ignore:
      - '**/*.md'
  pull_request_target:
    branches:
      - "master"
      - "release-*"
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-22.04
    outputs:
      app_version: ${{ steps.read_build_yaml.outputs.app_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Read build.yaml
        id: read_build_yaml
        run: echo "::set-output name=app_version::unstable-$(yq '.version' build.yaml)"

  call_linux_build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      actions_os: ubuntu-22.04
      dotnet_runtimes: '["linux-x64", "linux-musl-x64", "linux-arm64", "linux-arm"]'

  call_windows_build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      actions_os: windows-2022
      dotnet_runtimes: '["win-x64"]'

  call_osx_build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      actions_os: macos-11 #TODO: set to macos-12 later
      dotnet_runtimes: '["osx-x64"]'

  call_container_build:
    needs:
      - pre
      - call_linux_build
    uses: ./.github/workflows/_meta-container.yaml
    with:
      app_version: ${{ needs.pre.outputs.app_version }}
      publish_container: ${{ contains(github.repository_owner, 'jellyfin') && github.ref == 'refs/heads/master' }}
    secrets:
      registry_ghcr_usr: ${{ github.actor }}
      registry_ghcr_psw: ${{ secrets.GITHUB_TOKEN }}
      registry_quay_usr: ${{ secrets.QUAY_USR }}
      registry_quay_psw: ${{ secrets.QUAY_TKN }}
