name: "🏗️ Build CI"

on:
  push:
    branches:
      - "master"
      - "release-*"
  pull_request_target:
    branches:
      - "master"
      - "release-*"
  workflow_dispatch:

jobs:
  call_linux_build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      actions_os: ubuntu-22.04
      dotnet_runtimes: '["linux-x64", "linux-musl-x64", "linux-arm64", "linux-arm"]'

  call_windows_build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      actions_os: windows-2022
      dotnet_runtimes: '["win-x64"]'

  call_osx_build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      actions_os: macos-11 #TODO: set to macos-12 later
      dotnet_runtimes: '["osx-x64"]'

  call_container_build:
    needs:
      - call_linux_build
    uses: ./.github/workflows/_meta-container.yaml
    with:
      app_version: 10.8.0
      publish_container: false
