name: "🔬 Dependency Review"

on:
  pull_request:
    branches:
      - "master"
      - "release-*"

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2

      - name: Dependency Review
        uses: actions/dependency-review-action@v1.0.2
